project/models/film.py
""" class Film """

from datetime import date
from sqlalchemy import func
from project import db

class Film(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(70), nullable=False)
    year = db.Column(db.Integer)
    description = db.Column(db.String(500), nullable=False)
    release_date = db.Column(db.DateTime(timezone=True))
    duration = db.Column(db.Integer)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())

    def __init__(self, title: str, year: int, description: str, release_date: date, duration: int):
        self.title = title
        self.year = year
        self.description = description
        self.release_date = release_date
        self.duration = duration

    def __repr__(self) -> str:
        return f'<Film {self.title} {self.year}>'

project/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap5
from flask_sqlalchemy import SQLAlchemy

# configuration
app = Flask(__name__)
app.config.from_pyfile('config.py')

# bootstrap 5
bootstrap = Bootstrap5(app)

# En mode DEBUG uniquement, affichage de l'URI de la base de données
if app.config['DEBUG']:
    print("Database : " + app.config['SQLALCHEMY_DATABASE_URI'])

# config sqlalchemy
db = SQLAlchemy(app)

# page d'accueil
@app.get('/')
def home():
    return render_template('index.html')

# routes pour film
from .controllers import film_controller
app.register_blueprint(film_controller.film_app, url_prefix='/film')

project/controllers/film_controller.py
''' 
    routes pour l'entité Film
'''
from flask import Blueprint, render_template, Response, redirect, url_for, request
from project.form.film_form import FilmForm
from project.models.film import Film
from project import db

film_app = Blueprint('film_func', __name__)

@film_app.get('/')
def list() -> str:
    films = Film.query.all()
    return render_template('film/list.html', films=films)

@film_app.get('/<int:film_id>/')
def display(film_id: int) -> str:
    film = Film.query.get_or_404(film_id)
    return render_template('film/detail.html', film=film)

@film_app.post('/<int:film_id>/delete/')
def delete(film_id: int) -> Response:
    film = Film.query.get_or_404(film_id)
    db.session.delete(film)
    db.session.commit()
    return redirect(url_for('film_func.list'))

@film_app.route('/create/', methods=('GET', 'POST'))
def create() -> str | Response :
    form = FilmForm()

    if request.method == 'POST':
        if form.btn_return.data:
            return redirect(url_for('film_func.list'))

        if form.btn_cancel.data:
            return redirect(url_for('film_func.create'))
            
        if form.validate():
            film = Film(form.title.data, form.year.data, form.description.data, form.release_date.data, form.duration.data)
            db.session.add(film)
            db.session.commit()
            return redirect(url_for('film_func.list'))

    title = 'Add a New Film'
    return render_template('film/form.html', title=title, form = form)

@film_app.route('/<int:film_id>/form/', methods=('GET', 'POST'))
def edit(film_id: int) -> str | Response:

    form = FilmForm(film_id=film_id)

    if request.method == 'POST': 
        if form.btn_return.data:
            return redirect(url_for('film_func.list'))

        if form.btn_cancel.data:
            film: Film = Film.query.get_or_404(film_id)
            return redirect(url_for('film_func.edit', film_id=film.id))

        if form.validate():
            filmRecord: Film = Film.query.get_or_404(film_id)
            filmView = Film(form.title.data, form.year.data, form.description.data, form.release_date.data, form.duration.data)
            filmRecord.title = filmView.title
            filmRecord.year = filmView.year
            filmRecord.description = filmView.description
            filmRecord.release_date = filmView.release_date
            filmRecord.duration = filmView.duration
            db.session.add(filmRecord)
            db.session.commit()
            return redirect(url_for('film_func.list'))

    film: Film = Film.query.get_or_404(film_id)
    title = f'{film.title} {film.year} \'s Details ' 
    form.title.data = film.title
    form.year.data = film.year
    form.description.data = film.description
    form.release_date.data = film.release_date
    form.duration.data = film.duration
    return render_template('film/form.html', title=title, form=form)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <meta name="description" content="{% block description %}{% endblock %}" >
    <link rel="shortcut icon" href="{{ url_for('static', filename='image/logo.ico') }}">
    {{ bootstrap.load_css() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">
                <img src="{{ url_for('static', filename='image/logo.ico') }}" width="40" height="40" alt="Site logo">
                FlaskApp
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Accueil</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Film
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('film_func.list') }}">Liste</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('film_func.create') }}">Ajout</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#">A propos</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <main class="container">
        {% block content %} {% endblock %}
    </main>
    <footer>
      <div class="container mt-4">
        <div class="row">
          <ul class="nav justify-content-center">
            <li class="col-1 nav-item"><a href="/" aria-label="instagram"><i aria-hidden="true" class="bi bi-instagram"></i></a></li>
            <li class="col-1 nav-item"><a href="/" aria-label="twitter"><i aria-hidden="true" class="bi bi-twitter"></i></a></li>
            <li class="col-1 nav-item"><a href="/" aria-label="github"><i aria-hidden="true" class="bi bi-github"></i></a></li>
            <li class="col-1 nav-item"><a href="/" aria-label="facebook"><i aria-hidden="true" class="bi bi-facebook"></i></a></li>
          </ul>
        </div>
        <div class="row">
          <ul class="nav justify-content-center">
            <li class="col-2 nav-item"><a class="nav-link" href="/">Home</a></li>
            <li class="col-2 nav-item"><a class="nav-link" href="#">Services</a></li>
            <li class="col-2 nav-item"><a class="nav-link" href="#">About</a></li>
            <li class="col-2 nav-item"><a class="nav-link" href="#">Terms</a></li>
            <li class="col-2 nav-item"><a class="nav-link" href="#">Privacy Policy</a></li>
          </ul>
        </div>
        <div class="row">
          <p class="copyright">Copyright © Une vidéothèque fantastique 2022</p>
        </div>
      </div>
    </footer>
    {{ bootstrap.load_js() }}
</body>
</html>

project/templates/film/detail.html
{% extends 'base.html' %}
{% block description %} Film's details {% endblock %}

{% block content %}
<article class="col-12">
    <div class="row">
        <div class="card m-5">
            <div class="card-header">
                {% block title %} {{ film.title }} {{ film.year }}{% endblock %}
            </div>
            <div class="card-body">
                <p class="card-text">Title : {{ film.title }}</p>
                <p class="card-text">Year : {{ film.year }}</p>
                <p class="card-text">Release Date : {{ film.release_date.strftime("%Y-%m-%d") }}</p>
                <p class="card-text">Duration : {{ film.duration }} minutes</p>
                <p class="card-text">Joined : {{ film.created_at }}</p>
                <div class="card bg-gradient">
                    <div class="card-body">
                       <h3 class="card-title">Description</h3>
                       <p class="card-text">{{ film.description }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                <button id="returnButton" type="button" class="btn btn-dark"">Return</button>
            </div>
        </div>
    </div>
</article>

<script>
    document.getElementById('returnButton').addEventListener('click', () => {
        history.back();
    });
</script>

{% endblock %}

project/templates/film/form.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form, render_field, render_form_row %}

{% block content %}
    <h1 style="width: 100%">{% block title %} {{title}} {% endblock %}</h1>


    <form method="post">
        {{ form.csrf_token }}
        {{ render_form_row([form.title, form.year], col_map={'title': 'col-sm-12 col-md-9 col-lg-8 col-xl-8', 'year': 'col-sm-3 col-md-3 col-lg-4 col-xl-2'}) }}
        {{ render_field(form.description, class='description-textarea') }}
        {{ render_form_row([form.release_date], col_class_default='col-xs-4 col-sm-4 col-lg-2') }}
        {{ render_form_row([form.duration], col_class_default='col-xs-6 col-sm-2 col-lg-1') }}
        {{ render_field(form.btn_submit) }}
        {{ render_field(form.btn_cancel, button_style='secondary') }}
        {{ render_field(form.btn_return, button_style='dark') }}
    </form>

{% endblock %}

project/templates/film/list.html
{% extends 'base.html' %}
{% block description %} list of Films {% endblock %}

{% block content %}
    <div class="row">
        <h1>{% block title %} Films {% endblock %}</h1>
    </div>
    <div class="row gy-3">
        {% for film in films %}
        <article class="col-12 col-md-6 col-lg-3">
            <div class="card h-100">
                <div class="card-header">
                    film #{{film_id}}
                </div>
                <div class="card-body">
                    <h2 class="card-title">{{ film.title }} {{ film.year }}</h2>
                    <p class="card-text">{{ film.duration }} minutes</p>
                    <div class="card bg-gradient">
                        <div class="card-body">
                           <h3 class="card-title">Description</h3>
                           <p class="card-text">{{ film.description }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    <a class="btn btn-dark" href="{{ url_for('film_func.display', film_id=film.id)}}">Details</a>
                    <a class="btn btn-primary" href="{{ url_for('film_func.edit', film_id=film.id) }}">Edit</a>
                    <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{film.id}}">Delete</a>
                </div>
            </div>
        </article>

        <!-- Delete Modal -->
        <div class="modal fade" id="deleteModal{{film.id}}" tabindex="-1" aria-labelledby="deleteModalLabel{{film.id}}" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this film {{film}} ?
                </div>
                <div class="modal-footer">
                    <form method="post"
                        action="{{ url_for('film_func.delete', film_id=film.id) }}">
                        <button class="btn btn-dark" data-bs-dismiss="modal" type="reset">No</button>
                        <button class="btn btn-primary" type="submit">Yes</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>

{% endblock %}

project/templates/index.html
{% extends 'base.html' %}
{% block description %} cinémathèque bienvenue {% endblock %}

{% block content %}

    <div class="row">
      <div class="col">
        <article>
          <h1 class="m-md-5 text-center">Bienvenue dans notre fabuleuse cinémathèque !</h1>
        </article>
      </div>
    </div>
  
{% endblock %}